Resources:
  UsageDetailsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: ${self:custom.UsageDetailsBucketName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256