service: ${self:custom.package.name}

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-s3-cleaner
  - serverless-deployment-bucket
  - serverless-offline  # serverless-esbuild should precede serverless-offline or keep offline plugins at the end

frameworkVersion: '>=3.0.0 <4.0.0' # helps to be in same major version unless team wants to change

package:
  individually: true # helps in reducing the zip size of the lambdas,  hence faster deployments. Especially when deploying individual lambdas.

provider:
  name: aws
  architecture: arm64  # It's cost & performance effective. If errors are suspected on underlying architecture, comment this & test.
  runtime: nodejs14.x
  versionFunctions: false
  memorySize: 1024  # change it as per the need of memory
  timeout: 30 # default timeout
  logRetentionInDays: 14 # cloudwatch logs add some cost, mind it while increasing this configuration
  region: ${opt:region, 'eu-west-2'} # Change region as per your deployment region.
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL # can be PRIVATE if we want to restrict the accessibility of the endpoints to VPC resources only.
  deploymentBucket:
    name: ${self:service}.${self:provider.region}.deploys # Can be more descriptive
    serverSideEncryption: AES256
  stackPolicy: ${self:custom.stackPolicy} # helpful to define permissions, retention policies etc
  iamRoleStatements: [ ]
  tags:
    project: ${self:service}
    stage: ${self:provider.stage}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # useful for performance optimization, ref: http keep alive
    REGION: ${self:provider.region}

custom:
  env: ${file(./env/${self:provider.stage}.yml)}
  base: ${self:service}-${self:provider.stage}
  host: ${self:custom.env.DOMAIN}.${self:custom.env.ROOT_DOMAIN}
  package: ${file(./package.json)}
  stackPolicy: ${file(./env/stackPolicy.yml):${self:provider.stage}}
  serverless-iam-roles-per-function:  # lets to have iam policies at the global level & inherit at function level.
    defaultInherit: true
  UsageDetailsBucketName: ${self:service}-usage-details-sg
  serverless-s3-cleaner:
    # (optional) Whether to prompt before emptying a bucket. Default is 'false'.
    prompt: false
    # Names of buckets to remove before a stack is removed, or via 'sls s3clean' command
    buckets:
      - ${self:custom.UsageDetailsBucketName}
    # (optional) Buckets to remove before a stack is deployed.
  #    bucketsToCleanOnDeploy:
  #      - oldBucketName
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true

functions: # add your functions
  health:
    handler: src/health/index.handler
    name: ${self:custom.base}-health
    description: used as heartbeat lambda for this service
    events:
      - http:
          method: get
          cors: true
          path: health
resources:
  - ${file(resources/s3-usageDetails.yml)}
  - Outputs:
      UsageDetailsBucket:
        Description: Bucket that holds the files of usage details
        Value: ${self:custom.UsageDetailsBucketName}
        Export:
          # see Fn::ImportValue to use in other services
          # and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html for documentation on use.
          Name: ${self:custom.UsageDetailsBucketName}
